[package]
name = "cocomo-cli"
version = "0.0.1"
edition = "2024"

description = "CLI-App: COmpare, COpy & MOve directories and files."
documentation = "https://docs.rs/cocomo-cli/"
readme = "../README.md"
homepage = "https://github.com/mamrhein/cocomo"
repository = "https://github.com/mamrhein/cocomo"
license-file = "../LICENSE.TXT"
keywords = ["compare", "copy", "directory", "file", "move"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
cocomo-lib = { path = "../cocomo-lib" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
