[package]
name = "cocomo-lib"
version = "0.0.1"
edition = "2024"
authors = ["Michael Amrhein <michael@adrhinum.de>"]
description = "COmpare, COpy & MOve directories and files [core library]."
readme = "../README.md"
homepage = "https://github.com/mamrhein/cocomo"
repository = "https://github.com/mamrhein/cocomo"
documentation = "https://docs.rs/cocomo-lib/"
license-file = "../LICENSE.TXT"
keywords = ["directory", "file", "compare", "copy", "move"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
async-trait = "0.1"
blake3 = "1"
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
fs-err = { version = "3", features = ["tokio"] }
futures = "0.3"
parking_lot = "0.12"
thiserror = "2"
tokio = { version = "1", features = [
    "fs",
    "io-util",
    "sync",
    "macros",
    "rt-multi-thread",
] }
tokio-util = { version = "0.7", features = ["codec"] }
diff = "0.1"
regex = { version = "1", default-features = false, features = [
    "std",
    "perf",
    "unicode-perl",
] }
bitflags = "2"
globset = "0.4"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.22"
chacha20poly1305 = "0.10"
getrandom = "0.2"
hmac = "0.12"
sha2 = "0.10"
async_ftp = "6.0.0"
dirs = "6"
hex = "0.4"

[dev-dependencies]
temp-env = "0.3"
