# ---------------------------------------------------------------------------
# cocomo_gui — Desktop GUI for directory comparison
# ---------------------------------------------------------------------------

[package]
name = "cocomo-gui"
version = "0.0.1"
edition = "2024"
description = "GUI-App: COmpare, COpy & MOve directories and files."
documentation = "https://docs.rs/cocomo-gui/"
readme = "../README.md"
homepage = "https://github.com/mamrhein/cocomo"
repository = "https://github.com/mamrhein/cocomo"
license-file = "../LICENSE.TXT"
keywords = ["compare", "copy", "directory", "file", "move"]
categories = ["filesystem", "gui"]

[[bin]]
name = "cocomo-gui"
path = "src/main.rs"

[dependencies]
anyhow = "1"
cocomo-lib = { path = "../cocomo-lib" }
dirs = "6"
gpui-pre = "*"
gpui-pre-platform = "*"
log = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
