[package]
name = "cocomo-tui"
version = "0.0.1"
edition = "2024"
authors = ["Michael Amrhein <michael@adrhinum.de>"]
description = "TUI-App: COmpare, COpy & MOve directories and files."
readme = "../README.md"
homepage = "https://github.com/mamrhein/cocomo"
repository = "https://github.com/mamrhein/cocomo"
documentation = "https://docs.rs/cocomo-tui/"
license-file = "../LICENSE.TXT"
keywords = ["directory", "file", "compare", "copy", "move"]
categories = ["command-line-utilities", "filesystem"]

[[bin]]
name = "cocomo-tui"
path = "src/main.rs"

[dependencies]
cocomo-lib = { path = "../cocomo-lib" }
crossterm = "0.29"
ratatui = { version = "0.30", default-features = false, features = [
    "crossterm_0_29",
] }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
